#485539 [C#テキスト]1章演習問題
sharlettcho-being/C- pull request #1
Opened 2024-04-12 06:32 UTC by sharlettcho-being

第1章の演習問題

2024-04-18 10:25 UTC, ohdaira-being requested changes
動きに問題なく、理解されていることが分かりました。
主に読みやすいコードを書くための指摘を数点させていただきました。
指摘していない箇所も確認して、修正をお願いします！

2024-04-18 10:25 UTC, odaira1119 commented on 章未問題1/Practice1-1-1/Product.cs
> +        public int Code { get; set; }
プロパティにヘッダーコメントで説明していて、読みやすくなっていて、goodです！
さらに読みやすくする方法がありますので、紹介します。
`/// `で始まる**XMLドキュメンテーションコメント**というものです。
以下の記事を読んで、コメントの修正をお願いいたします。
https://qiita.com/matsumoyu/items/5930cc7ffe2f4f4aafa2

2024-04-18 10:25 UTC, odaira1119 commented on 章未問題1/Practice1-1-1/Product.cs
> +            return (int)(Price * 0.08);
Gaia Cloudのコーディング規約として、
自クラスのプロパティを参照するときは、`this`を付ける
というルールがあります。
なので、`Price`プロパティにthisをつけてください。

2024-04-18 10:25 UTC, odaira1119 commented on 章未問題1/Practice1-1-1/Product.cs
> +            return (int)(Price * 0.08);
また、その他の個所でも`this`がついていないところがありますので、修正をお願いいたします！

2024-04-18 10:25 UTC, ohdaira-being commented on 章未問題1/Practice1-1-1/Program1-1-1.cs
> +            OtherName.Product product = new OtherName.Product();
* `OtherName.Product`について
namespaceを変えられているようですが、今回の場合は同じnamespaceの方が適切ですので、
同じnamespaceを使うように修正お願いいたします。

2024-04-18 10:25 UTC, ohdaira-being commented on 章未問題1/Practice1-1-1/Program1-1-1.cs
> +            OtherName.Product product = new OtherName.Product();
また、変数名に関しては以下のルールがありますので、ローカル変数の修正お願いします。
フィールド変数：接頭字F＋最初の文字大文字
ローカル変数：接頭字w＋最初の文字大文字
引数：接頭辞v＋最初の文字大文字

2024-04-18 10:25 UTC, ohdaira-being commented on 章未問題1/Practice1-1-2/Program1-1-2.cs
> +            MyClass myClass = new MyClass(1, 2);
右辺から型が明らかな場合は、varを使うようにしてください。

2024-04-18 10:25 UTC, ohdaira-being commented on 章未問題1/Practice1-1-2/Program1-1-2.cs
> +            Console.WriteLine("構造体の値　({0}, {1})", myStruct.X, myStruct.Y);
可読性のために文字列補間式で書くようにしてください。

2024-04-19 01:24 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-1/Product.cs
> +        public int Code { get; set; }
修正致しました。

2024-04-19 01:24 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-1/Product.cs
> +            return (int)(Price * 0.08);
修正しました。

2024-04-19 01:25 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-1/Program1-1-1.cs
> +            OtherName.Product product = new OtherName.Product();
修正しました。

2024-04-19 01:25 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-2/Program1-1-2.cs
> +            MyClass myClass = new MyClass(1, 2);
修正しました。

2024-04-19 01:25 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-2/Program1-1-2.cs
> +            Console.WriteLine("構造体の値　({0}, {1})", myStruct.X, myStruct.Y);
修正しました。

2024-04-23 11:26 UTC, ohdaira-being requested changes
再度指摘しましたので、ご確認ください。

2024-04-23 11:26 UTC, ohdaira-being commented on 章未問題1/Practice1-1-1/Product.cs
> +        public int FCode { get; set; }
コーディング規約で、プロパティには接頭辞を付けないルールとなっています。
接頭辞のFを削除するように修正お願いします。
また、他のプロパティも同様ですので、修正お願いします。

2024-04-23 11:26 UTC, ohdaira-being commented on 章未問題1/Practice1-1-1/Product.cs
> +        }
`<returns></returns>`に戻り値の説明を記載してください。

2024-04-23 11:26 UTC, ohdaira-being commented on 章未問題1/Practice1-1-2/Program1-1-2.cs
> +            public MyClass(int x, int y)
コンストラクタの引数にも以下のコーディング規約適用されますので、修正お願いします。
引数：接頭辞v＋最初の文字大文字

2024-04-23 11:26 UTC, ohdaira-being commented on 章未問題1/Practice1-1-2/Program1-1-2.cs
> +            var FmyClass = new MyClass(1, 2);
Fmyclassは、Mainメソッド内のローカル変数です。
なので、Fではなくwを付けるようにしてください。
他にもローカル変数にFを付けている個所の修正をお願いします。

2024-04-23 11:26 UTC, ohdaira-being commented on 章未問題1/Practice1-1-3/Person.cs
> +            DateTime today = DateTime.Today;
こちらも右辺から型が明らかなので、varで十分です。
また、ローカル変数の接頭辞を付けるようにしてください。

2024-04-23 11:26 UTC, ohdaira-being commented on 章未問題1/Practice1-1-1/Product.cs
> +using System.Threading.Tasks;
不要なusingは、削除するようにお願いします。
（💡マークから簡単に不要なusingを削除できます。）
他のcsファイルも同様です。

2024-04-24 00:29 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-1/Product.cs
> +        public int FCode { get; set; }
修正しました。

2024-04-24 00:32 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-1/Product.cs
> +        }
修正しました。

2024-04-24 00:35 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-2/Program1-1-2.cs
> +            public MyClass(int x, int y)
修正しました。

2024-04-24 00:42 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-2/Program1-1-2.cs
> +            var FmyClass = new MyClass(1, 2);
修正しました。
すみませんが、１つ質問させてください。
Mainメソッドで 
「Student FStudent = new Student();」ならインスタンス作成という意味でFを付ける必要で
「Person wPerson = new Student(1, 2, "チョ", DateTime.Parse("2018-4-10"));」ならインスタンス作成ですが、wPersonは変数と認識する必要でしょうか。

2024-04-24 00:45 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-3/Person.cs
> +            DateTime today = DateTime.Today;
修正しました。

2024-04-24 00:47 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-1/Product.cs
> +using System.Threading.Tasks;
修正しました。

2024-04-25 08:10 UTC, ohdaira-being requested changes
ご確認のほどよろしくお願いします

2024-04-25 08:10 UTC, odaira1119 commented on 章未問題1/Practice1-1-1/Program1-1-1.cs
> +            Product FProduct = new Product();
こちら右辺から型が明らかなので、varにしておきましょう
また、変数名にフィールド変数のコーディング規約が適用されていますので、ローカル変数のコーディング規約に従って書き直してください。

2024-04-25 08:10 UTC, odaira1119 commented on 章未問題1/Practice1-1-1/Product.cs
> +    internal class Product{
クラスにもドキュメンテーションコメントを付けるようにお願いします。
基本的に、クラス・publicメソッド（コンストラクタ含む）・プロパティには、付けると覚えておいてください！

2024-04-25 08:10 UTC, odaira1119 commented on 章未問題1/Practice1-1-2/Program1-1-2.cs
> +            public MyStruct(int vX, int vY){
コンストラクタにもドキュメンテーションコメントを付けてください。

2024-04-25 08:10 UTC, odaira1119 commented on 章未問題1/Practice1-1-3/Program1-1-3.cs
> +            Student FStudent = new Student();
右辺から型が明らかですね。
また、ローカル変数ですので、接頭辞を修正してください。

2024-04-25 08:10 UTC, odaira1119 commented on 章未問題1/Practice1-1-3/Program1-1-3.cs
> +            FStudent.ClassNumber = 1;
`FStudent`のプロパティを個別で代入していますが、
せっかくコンストラクタを作りましたので、コンストラクタを使って代入するように修正してください。

2024-04-25 08:10 UTC, odaira1119 commented on 章未問題1/Practice1-1-3/Program1-1-3.cs
> +            wPerson.Birthday = DateTime.Parse("2012 / 4 / 6");
`wPerson`のName とBirthday 、Grade、ClassNumberは、すでにコンストラクタを経由して代入されていますので、不要な代入かと思います。
不要なコードを削除してください。

2024-04-25 08:10 UTC, ohdaira-being commented on 章未問題1/Practice1-1-3/Program1-1-3.cs
> +            Person wPerson = new Student(1, 2, "チョ", DateTime.Parse("2018-4-10"));
`Person`型の変数に`Student`型を代入した理由はありますか？
基本的にインスタンス生成時（newするとき）は、そのコンストラクタの型が作られるため、違和感を感じました。
もしも、特に理由がない場合は、`Student`型の変数で宣言するのが良いと思います。

また、`Person`にしたため、直後のコードでキャスト（`(Student)wPerson`）する必要が発生しています。
補足：`(Student)wPerson`の`()`は、キャスト演算子といいます。

2024-04-25 08:10 UTC, ohdaira-being commented on 章未問題1/Practice1-1-3/Person.cs
> +            if (wToday < Birthday.AddYears(wAge))
`Birthday`は、自クラスのプロパティなので、`this`を付けてください

2024-04-25 08:21 UTC, ohdaira-being commented on 章未問題1/Practice1-1-2/Program1-1-2.cs
> +            var FmyClass = new MyClass(1, 2);
ローカル変数とフィールド変数の違いについて、ご質問ありがとうございます。
まず、以下の書き方は共にインスタンス生成です。
`Student FStudent = new Student();`
`Person wPerson = new Student(1, 2, "チョ", DateTime.Parse("2018-4-10"));`
インスタンス生成は、`new`キーワードを使うのがポイントですね。

次に、ローカル変数なのか？フィールド変数なのか？についてです。
違いは色々あるのですが、一番判別しやすいのは、宣言場所です。
* ローカル変数
メソッドやプロパティ、イベントハンドラ内で宣言された変数
* フィールド変数
クラス・構造体の直下で宣言された変数

他にも違いはありますので、一度調べて整理しておくといいと思いますよ

2024-04-25 08:31 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-1/Program1-1-1.cs
> +            Product FProduct = new Product();
修正しました。

2024-04-25 08:33 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-1/Product.cs
> +    internal class Product{
修正しました。

2024-04-25 08:44 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-2/Program1-1-2.cs
> +            public MyStruct(int vX, int vY){
修正しました。

2024-04-25 08:45 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-3/Program1-1-3.cs
> +            Student FStudent = new Student();
修正しました。

2024-04-25 08:48 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-3/Program1-1-3.cs
> +            FStudent.ClassNumber = 1;
修正しました。

2024-04-25 08:49 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-3/Program1-1-3.cs
> +            wPerson.Birthday = DateTime.Parse("2012 / 4 / 6");
修正しました。

2024-04-25 08:53 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-3/Program1-1-3.cs
> +            Person wPerson = new Student(1, 2, "チョ", DateTime.Parse("2018-4-10"));
演習問題では「２で発生したインスタンス（２で発生したのはStudentクラスです。）をPerson型及びobject型の変数に代入できることを確認してください。」言われてのでPerson型の変数にStudent型を代入したのです。
よろしくお願いします。

2024-04-25 08:54 UTC, sharlettcho-being commented on 章未問題1/Practice1-1-3/Person.cs
> +            if (wToday < Birthday.AddYears(wAge))
修正しました。

2024-05-08 01:06 UTC, ohdaira-being commented on 章未問題1/Practice1-1-3/Program1-1-3.cs
> +            Person wPerson = new Student(1, 2, "チョ", DateTime.Parse("2018-4-10"));
そういうことでしたか。ありがとうございます。

2024-05-08 02:23 UTC, merged