#485963 [C#テキスト]10章演習問題
sharlettcho-being/C- pull request #10
Opened 2024-04-30 02:07 UTC by sharlettcho-being

10章の演習問題を解きました。

2024-05-13 02:58 UTC, ohdaira-being reviewed
動作確認のために、コードを実行するテキストファイルも提出してください。
よろしくお願いします。

2024-05-13 02:58 UTC, ohdaira-being commented on 章未問題10/Practice10-1-2/Program10-1-2.cs
> +            var wFilePath = @"C:\Users\sharlettcho\Desktop\Sample10-2.txt";
相対パスにしましょう

2024-05-13 02:58 UTC, ohdaira-being commented on 章未問題10/Practice10-1-2/Program10-1-2.cs
> +            if (File.Exists(wFilePath)) {
ガード節でネストを浅くしてください。

2024-05-13 02:58 UTC, ohdaira-being commented on 章未問題10/Practice10-1-3/Program10-1-3.cs
> +                    Console.WriteLine("{0}{1}", wString.Index, wString.Value);
文字列補完で書きましょう

2024-05-13 02:58 UTC, ohdaira-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +            var wFilePath = @"C:\Users\sharlettcho\Desktop\Sample10-4.txt";
相対パスで記載してください。

2024-05-13 02:58 UTC, ohdaira-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +                if (File.Exists(wFilePath)) {
同じif文が続いていますので、不要なものは削除してください。
また、ネストが深いのでガード節で浅くしてください。

2024-05-13 02:58 UTC, ohdaira-being commented on 章未問題10/Practice10-1-5/Program10-1-5.cs
> +            var wFilePath = @"C:\Users\sharlettcho\Desktop\Sample10-5.html";
相対パスで記載してください。

2024-05-13 02:58 UTC, ohdaira-being commented on 章未問題10/Practice10-1-5/Program10-1-5.cs
> +                if (File.Exists(wFilePath)) {
こちらも同じif文が続いていますので、修正お願いします。

2024-05-13 05:05 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-2/Program10-1-2.cs
> +            var wFilePath = @"C:\Users\sharlettcho\Desktop\Sample10-2.txt";
修正しました。

2024-05-13 05:07 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-2/Program10-1-2.cs
> +            if (File.Exists(wFilePath)) {
修正しました。

2024-05-13 05:08 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-3/Program10-1-3.cs
> +                    Console.WriteLine("{0}{1}", wString.Index, wString.Value);
修正しました。

2024-05-13 05:10 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +            var wFilePath = @"C:\Users\sharlettcho\Desktop\Sample10-4.txt";
修正しました。

2024-05-13 05:12 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +                if (File.Exists(wFilePath)) {
修正しました。

2024-05-13 05:16 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-5/Program10-1-5.cs
> +            var wFilePath = @"C:\Users\sharlettcho\Desktop\Sample10-5.html";
修正しました。

2024-05-13 05:16 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-5/Program10-1-5.cs
> +                if (File.Exists(wFilePath)) {
修正しました。

2024-05-14 02:00 UTC, ohdaira-being requested changes
数点指摘しました。
指摘された内容と同様のことが他の個所でもないか？も確認しておくと修正スピードが上がるかと思います。
よろしくお願いします。

2024-05-14 02:00 UTC, ohdaira-being commented on 章未問題10/Practice10-1-2/Program10-1-2.cs
> +            string wRelativePath = @"..\..\Sample10-2.txt";
該当のファイルをプッシュしてください。

2024-05-14 02:00 UTC, ohdaira-being commented on 章未問題10/Practice10-1-3/Program10-1-3.cs
> +            }
不要なスペースが10個ほど入っていますので、削除してください。

2024-05-14 02:00 UTC, ohdaira-being commented on 章未問題10/Practice10-1-3/Program10-1-3.cs
> +            //初期化
可読性のための決まりとして、コードを読めば分かることはコメントしないというものがあります。
少しずつこういったコメントを減らしていきましょう。
ここの初期化というのは、コードを読めば分かる かつ 何が初期化されるのかという重要な内容が抜けていますので、不要かと思います

2024-05-14 02:00 UTC, ohdaira-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +            string wRelativePath = @"..\..\Sample10-4.txt";
該当のファイルをプッシュしてください。

2024-05-14 02:00 UTC, ohdaira-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +                if (!File.Exists(wFilePath)) return;
インデントがずれていますので、修正してください。

2024-05-14 02:00 UTC, ohdaira-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +            using (StreamWriter wWriter = new StreamWriter(wFilePath)) {
右辺から型が明示的なので、varにしておきましょう

2024-05-14 02:00 UTC, ohdaira-being commented on 章未問題10/Practice10-1-5/Program10-1-5.cs
> +            string wRelativePath = @"..\..\Sample10-5.html";
ファイルをプッシュしてください。

2024-05-14 02:00 UTC, ohdaira-being commented on 章未問題10/Practice10-1-5/Program10-1-5.cs
> +            using (StreamWriter wWriter = new StreamWriter(wFilePath)) {
varで十分です。

2024-05-14 02:00 UTC, ohdaira-being commented on 章未問題10/Practice10-1-6/Program10-1-6.cs
> +        /// <param name="args"></param>
こちらのコメントは不要です。

2024-05-14 02:30 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-2/Program10-1-2.cs
> +            var wFilePath = @"C:\Users\sharlettcho\Desktop\Sample10-2.txt";
動作確認のために、コードを実行するテキストファイルも提出しました。

2024-05-14 02:31 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-2/Program10-1-2.cs
> +            string wRelativePath = @"..\..\Sample10-2.txt";
該当のファイルをプッシュしました。

2024-05-14 02:35 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-3/Program10-1-3.cs
> +            }
不要なスペースを削除しました。他の箇所にも削除しました。

2024-05-14 02:36 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-3/Program10-1-3.cs
> +            //初期化
初期化というコメントを削除しました。

2024-05-14 02:36 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +            string wRelativePath = @"..\..\Sample10-4.txt";
該当のファイルをプッシュしました。

2024-05-14 02:36 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +                if (!File.Exists(wFilePath)) return;
修正しました。

2024-05-14 02:39 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +            using (StreamWriter wWriter = new StreamWriter(wFilePath)) {
string[] wLines を var wLinesに変更しました。

2024-05-14 02:39 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-5/Program10-1-5.cs
> +            string wRelativePath = @"..\..\Sample10-5.html";
ファイルをプッシュしました。

2024-05-14 02:39 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-5/Program10-1-5.cs
> +            using (StreamWriter wWriter = new StreamWriter(wFilePath)) {
string[] wLines を var wLinesに変更しました。

2024-05-14 02:40 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-6/Program10-1-6.cs
> +        /// <param name="args"></param>
コメントを削除しました。

2024-05-15 02:35 UTC, ohdaira-being commented on 章未問題10/Practice10-1-2/Program10-1-2.cs
> +            var wFilePath = @"C:\Users\sharlettcho\Desktop\Sample10-2.txt";
ありがとうございます！

以前の指摘と同様ですが、カレントディレクトリパスの取得とCombine()は不要となりますので、削除お願いします。

2024-05-15 02:48 UTC, ohdaira-being reviewed
ご確認のほどよろしくお願いします！

2024-05-15 02:48 UTC, ohdaira-being commented on 章未問題10/Practice10-1-1/Program10-1-1.cs
> +            }else {
細かくてすみません。
`}`と`else`の間に半角スペースを入れてください

2024-05-15 02:48 UTC, ohdaira-being commented on 章未問題10/Practice10-1-2/Program10-1-2.cs
> +                }
ここに不要なスペースがありますので、削除お願いします。

2024-05-15 02:48 UTC, ohdaira-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +            var wFilePath = @"C:\Users\sharlettcho\Desktop\Sample10-4.txt";
相対パスのみで十分です。

2024-05-15 02:48 UTC, ohdaira-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +                if (File.Exists(wFilePath)) {
まだ同じ行が繰り返されています。
不要なコードを削除してください。

2024-05-15 02:48 UTC, ohdaira-being commented on 章未問題10/Practice10-1-5/Program10-1-5.cs
> +            var wFilePath = @"C:\Users\sharlettcho\Desktop\Sample10-5.html";
これまでと同様にパスの修正をお願いします。

2024-05-15 02:48 UTC, ohdaira-being commented on 章未問題10/Practice10-1-5/Program10-1-5.cs
> +                if (File.Exists(wFilePath)) {
まだ同じ行が続いていますので、不要なコードを削除してください。

2024-05-15 02:48 UTC, ohdaira-being commented on 章未問題10/Practice10-1-3/Program10-1-3.cs
> +            }
まだ消えていないようです。
19行目の`}`の後ろにあります。

2024-05-15 02:48 UTC, ohdaira-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +            using (StreamWriter wWriter = new StreamWriter(wFilePath)) {
`using()`内の`wWriter `です

2024-05-15 02:48 UTC, ohdaira-being commented on 章未問題10/Practice10-1-5/Program10-1-5.cs
> +            using (StreamWriter wWriter = new StreamWriter(wFilePath)) {
`wWriter `です！

2024-05-15 04:29 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-2/Program10-1-2.cs
> +            var wFilePath = @"C:\Users\sharlettcho\Desktop\Sample10-2.txt";
Combine()を削除しました。

2024-05-15 04:30 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +            var wFilePath = @"C:\Users\sharlettcho\Desktop\Sample10-4.txt";
Combine()を削除しました。

2024-05-15 04:30 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +                if (File.Exists(wFilePath)) {
削除しました。

2024-05-15 04:31 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-5/Program10-1-5.cs
> +            var wFilePath = @"C:\Users\sharlettcho\Desktop\Sample10-5.html";
修正しました。

2024-05-15 04:32 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-5/Program10-1-5.cs
> +                if (File.Exists(wFilePath)) {
不要なコードを削除しました。

2024-05-15 04:34 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-3/Program10-1-3.cs
> +            }
不要なスペースを削除しました。以前はスペースの確認が明らかにできませんでしたが、設定で テキストエディター>全般 にある空白の表示にチェックを入れておくと見やすくなりました。
有難うございました。

2024-05-15 04:35 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-4/Program10-1-4.cs
> +            using (StreamWriter wWriter = new StreamWriter(wFilePath)) {
wWriterにもvar にしました。

2024-05-15 04:36 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-5/Program10-1-5.cs
> +            using (StreamWriter wWriter = new StreamWriter(wFilePath)) {
wWriterにもvar にしました。

2024-05-15 04:36 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-1/Program10-1-1.cs
> +            }else {
スペースを入れました。

2024-05-15 04:36 UTC, sharlettcho-being commented on 章未問題10/Practice10-1-2/Program10-1-2.cs
> +                }
不要なスペースを削除しました。

2024-05-16 01:06 UTC, ohdaira-being commented on 章未問題10/Practice10-1-3/Program10-1-3.cs
> +            }
それは良かったです！
私ももっと早く共有しておけば…。
これから便利なものがあれば、積極的に共有していきます。

2024-05-16 01:45 UTC, merged