#485964 [C#テキスト]11章演習問題
sharlettcho-being/C- pull request #11
Opened 2024-04-30 07:47 UTC by sharlettcho-being

11章の演習問題を解きました。

2024-05-14 02:23 UTC, ohdaira-being requested changes
修正をお願いします！

2024-05-14 02:23 UTC, ohdaira-being commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +            string wXMLFilePath = "C:\\Users\\sharlettcho\\Desktop\\Sample11-1.xml";
該当のファイルのプッシュと相対パスへ書き直しをお願いします。

2024-05-14 02:23 UTC, odaira1119 commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +        /// <param name="args"></param>
Mainメソッドに対してコメントは不要です

2024-05-14 02:23 UTC, odaira1119 commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +        /// <param name="vElements"></param>
引数に対するコメントも追記してください
下に同様の個所がありますので、併せて修正してください。

2024-05-14 02:23 UTC, odaira1119 commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +                Console.WriteLine("{0} : {1}", wName.Value, wTeamMember.Value);
文字列補完で書いておきましょう

2024-05-14 02:23 UTC, odaira1119 commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +            var wPlayerList = vElements.OrderBy(x => (int.Parse(x.Element("firstplayed").Value)));
`(int.Parse(...))`の外側の`()`は、不要ですので削除してください

2024-05-14 02:23 UTC, odaira1119 commented on 章未問題11/Practice11-1-2/Program11-1-2.cs
> +            string wXMLFilePath = "C:\\Users\\sharlettcho\\Desktop\\Sample11-2.xml";
パスの修正とファイルの提出をお願いします。

2024-05-14 02:23 UTC, odaira1119 commented on 章未問題11/Practice11-1-2/Program11-1-2.cs
> +                    wXDoc.Root.Elements("word").Select(x =>
インデントがずれていますので、正してください

2024-05-14 02:23 UTC, odaira1119 commented on 章未問題11/Practice11-1-2/Program11-1-2.cs
> +            wNewDoc.Save("C:\\Users\\sharlettcho\\Desktop\\Sample11 -2New.xml");
保存先パスも個人のパスとなっていますので、修正方法を考え、誰が起動してもエラーにならないようにしてください。

2024-05-14 02:50 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +            string wXMLFilePath = "C:\\Users\\sharlettcho\\Desktop\\Sample11-1.xml";
該当のファイルのプッシュと相対パスへ書き直しました。

2024-05-14 02:50 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +        /// <param name="args"></param>
コメントを削除しました。

2024-05-14 02:53 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +        /// <param name="vElements"></param>
修正しました。

2024-05-14 02:54 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +                Console.WriteLine("{0} : {1}", wName.Value, wTeamMember.Value);
文字列補完で書き直しました。

2024-05-14 02:54 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +            var wPlayerList = vElements.OrderBy(x => (int.Parse(x.Element("firstplayed").Value)));
括弧を削除しました。

2024-05-14 02:56 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-2/Program11-1-2.cs
> +            string wXMLFilePath = "C:\\Users\\sharlettcho\\Desktop\\Sample11-2.xml";
相当パスに変更し、提出もしました。

2024-05-14 03:01 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-2/Program11-1-2.cs
> +                    wXDoc.Root.Elements("word").Select(x =>
修正しました。

2024-05-14 03:01 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-2/Program11-1-2.cs
> +            wNewDoc.Save("C:\\Users\\sharlettcho\\Desktop\\Sample11 -2New.xml");
保存パスも相当パスに変更しました。

2024-05-15 02:52 UTC, ohdaira-being commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +            string wXMLFilePath = "C:\\Users\\sharlettcho\\Desktop\\Sample11-1.xml";
カレントディレクトリパスの取得とCombineは不要ですので、修正お願いします。

2024-05-15 02:54 UTC, ohdaira-being commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +        /// <param name="vElements"></param>
`DisplaySportWithMostMember`メソッドの引数に対するコメントが抜けていますので、追記お願いします。

2024-05-15 02:55 UTC, ohdaira-being commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +            var wPlayerList = vElements.OrderBy(x => (int.Parse(x.Element("firstplayed").Value)));
消えていないようです。

2024-05-15 03:01 UTC, ohdaira-being reviewed
再度、ご確認のほどよろしくお願いします

2024-05-15 03:01 UTC, odaira1119 commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +            XElement soccerElement = new XElement("ballsport",
こちらも右辺から明らかなので、varにしておきましょう
基本的にnewするときは、varで十分です。

2024-05-15 03:01 UTC, odaira1119 commented on 章未問題11/Practice11-1-2/Program11-1-2.cs
> +            string wXMLFilePath = "C:\\Users\\sharlettcho\\Desktop\\Sample11-2.xml";
パスの修正をお願いします。

2024-05-15 03:01 UTC, odaira1119 commented on 章未問題11/Practice11-1-2/Program11-1-2.cs
> +                    wXDoc.Root.Elements("word").Select(x =>
まだずれています。
一旦、上の行と同じ行にしてから、改行すると正しいインデントがどこなのかが分かるかと思います。

2024-05-15 04:43 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +            string wXMLFilePath = "C:\\Users\\sharlettcho\\Desktop\\Sample11-1.xml";
Combineを削除しました。

2024-05-15 04:44 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +        /// <param name="vElements"></param>
コメントをつけました。

2024-05-15 04:46 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +            var wPlayerList = vElements.OrderBy(x => (int.Parse(x.Element("firstplayed").Value)));
すみません、削除しました。

2024-05-15 04:47 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-2/Program11-1-2.cs
> +            string wXMLFilePath = "C:\\Users\\sharlettcho\\Desktop\\Sample11-2.xml";
パスを修正しました。

2024-05-15 04:51 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-2/Program11-1-2.cs
> +                    wXDoc.Root.Elements("word").Select(x =>
修正しました。

2024-05-15 04:52 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +            XElement soccerElement = new XElement("ballsport",
varに変更しました。

2024-05-16 01:24 UTC, ohdaira-being commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +            new XElement("firstplayed", vSoccerFirstPlayed));
インデントがずれており、読みずらくなっています。
正しいインデントになるように修正お願いします。

2024-05-16 01:24 UTC, ohdaira-being commented on 章未問題11/Practice11-1-2/Program11-1-2.cs
> +            XDocument wNewDoc = new XDocument(
こちらもvarにしておきましょう

2024-05-16 01:39 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-1/Program11-1-1.cs
> +            new XElement("firstplayed", vSoccerFirstPlayed));
インデントを修正しました。

2024-05-16 01:42 UTC, sharlettcho-being commented on 章未問題11/Practice11-1-2/Program11-1-2.cs
> +            XDocument wNewDoc = new XDocument(
何度も教えてくれましたが、気づかないですみません。
varに変更しました。

2024-05-17 02:08 UTC, merged