#485953 [C#テキスト]2章演習問題
sharlettcho-being/C- pull request #2
Opened 2024-04-16 02:13 UTC by sharlettcho-being

2章の演習問題を解きました。

2024-04-18 10:06 UTC, k-miyahara-being requested changes
動作としては問題ないと思います！
あとはコードをきれいにするということを気にしてみると良いと思います

いくつか指摘しましたが、ある箇所で指摘された内容は、他の箇所でも同じ指摘がないようにあわせて確認・修正をお願いします。

2024-04-18 10:06 UTC, k-miyahara-being commented on 章未問題2/Practice2-1-1/Program2-2-1.cs
[Visual Studioの設定ファイル](https://dev-redmine.being.group/projects/sirius-client/wiki/%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83%E3%81%AE%E6%A7%8B%E7%AF%89%E6%89%8B%E9%A0%86#4-Visual-Studio-%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%82%92%E7%B5%B1%E4%B8%80%E3%81%99%E3%82%8B)はインポート済みでしょうか？
クラスやメソッドの開始のかっこ `{` の位置が次の行になっているのが気になりました。
コーディング規約では、↓のような位置になるように決められています。これは、上記の設定ファイルをインポートしておくことでVisual Studioが自動でやってくれるようになります。
```
namespace Practice2_1_1 {
    internal class Program {
        static void Main(string[] args) {
```

よくわからなければ、大平君に聞いてみてください。

Visual Studioのツール>オプション>テキストエディタ―>C#>コードスタイル>書式設定>改行 からも設定できます。
![スクリーンショット 2024-04-18 184504](https://github.com/sharlettcho-being/C-/assets/86827185/5d1a9418-f3fe-4838-963d-74be2776951d)

2024-04-18 10:06 UTC, k-miyahara-being commented on 章未問題2/Practice2-1-1/Song.cs
> +        public int wLength { get; set; }
接頭辞`w`はローカル変数につけるものなので、ここでは必要ありません。
プロパティは接頭辞なしとなっています。

[コーディング規約 > 接頭辞](https://dev-redmine.being.group/projects/sirius-client/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#%E6%8E%A5%E9%A0%AD%E8%BE%9E)

2024-04-18 10:06 UTC, k-miyahara-being commented on 章未問題2/Practice2-1-1/Song.cs
> +        }
クラス、プロパティ、コンストラクタ、publicなメソッドには[ドキュメントコメント](https://learn.microsoft.com/ja-jp/visualstudio/ide/reference/generate-xml-documentation-comments?view=vs-2022)をつけるようにしてください。

これにより、そのプロパティやメソッドをマウスホバーしたときに一緒にコメントが表示されるようになります。
クラス外からプロパティを使うときなどに、そのプロパティが定義されているクラスにわざわざ移動して確認する必要がなくなるため、非常に役立ちます。

![image](https://github.com/teshima-being/TextC/assets/86827185/021b504f-98e5-439f-8ba0-208f50437455)

プロパティやメソッドの1つ上の行で`///` (スラッシュ3つ)と入力することで自動で補完してくれるので、やってみてください。

[コーディング規約 > コメント](https://dev-redmine.being.group/projects/sirius-client/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88)にも記載があります。

2024-04-18 10:06 UTC, k-miyahara-being commented on 章未問題2/Practice2-1-1/Program2-2-1.cs
> +using System.Threading.Tasks;
不要なusingは削除してください。
Visual Studioでマウスホバーすると、↓のようなメッセージが出ると思うので、電球💡アイコンを押下すると削除するメニューが現れて自動で消してくれたりします。
![image](https://github.com/teshima-being/TextC/assets/86827185/e61fc923-c5d7-4a0d-963b-16bab25f30b8)

この電球アイコンがあるときはコードの改善を提案してくれているので、また機会があれば見てみてください

2024-04-18 10:06 UTC, k-miyahara-being commented on 章未問題2/Practice2-2-2/InchesConverter.cs
> +        public static readonly double C_RATIO = 0.0254;
定数の命名について、すべて大文字にする必要はありません。
`C_Ratio`でOKです

2024-04-18 10:06 UTC, k-miyahara-being commented on 章未問題2/Practice2-2-2/Program2-2-2.cs
> +                Console.WriteLine("{0} in = {1:0.0000}m", i, wMeter);
`"{0} in = {1:0.0000}m", i, wMeter`
↑は、文字列補間式というもので書き換えることができます。
書き換えると、
`$"{i} in = {wMeter:0.0000}m"`
となります。
`””`の前に`$`を書いて、`{0}`、`{1}`としていたところに直接変数を埋め込みます。

変数を文字列に埋め込むことができるので読みやすくなります。
試してみてください。

2024-04-18 10:06 UTC, k-miyahara-being commented on 章未問題2/Practice2-2-3/Program.cs
> +            Dictionary<string, int> amountPerStore = sales.GetPerStoreSales();
ローカル変数の接頭辞がありません。

2024-04-19 02:53 UTC, sharlettcho-being commented on 章未問題2/Practice2-2-2/InchesConverter.cs
> +        public static readonly double C_RATIO = 0.0254;
修正しました。

2024-04-19 02:56 UTC, sharlettcho-being commented on 章未問題2/Practice2-2-2/Program2-2-2.cs
> +                Console.WriteLine("{0} in = {1:0.0000}m", i, wMeter);
修正しました。

2024-04-19 02:58 UTC, sharlettcho-being commented on 章未問題2/Practice2-2-3/Program.cs
> +            Dictionary<string, int> amountPerStore = sales.GetPerStoreSales();
修正しました。

2024-04-19 02:58 UTC, sharlettcho-being commented on 章未問題2/Practice2-1-1/Program2-2-1.cs
> +using System.Threading.Tasks;
修正しました。

2024-04-19 02:58 UTC, sharlettcho-being commented on 章未問題2/Practice2-1-1/Song.cs
> +        }
修正しました。

2024-04-19 02:58 UTC, sharlettcho-being commented on 章未問題2/Practice2-1-1/Program2-2-1.cs
修正しました。

2024-04-19 03:58 UTC, sharlettcho-being commented on 章未問題2/Practice2-1-1/Song.cs
> +        public int wLength { get; set; }
修正しました。

2024-04-22 01:55 UTC, k-miyahara-being requested changes
あと少しです！

2024-04-22 01:55 UTC, k-miyahara-being commented on 章未問題2/Practice2-1-1/Song.cs
> +        /// <param name="vLength"></param>
ドキュメントコメントの<param>タグでは、引数の説明を記入できます。
↓のように、開始タグと終了タグの間に、その引数が何を表すものなのか説明を加えてください。
`/// <param name="vTitle">タイトル</param>`

メソッドや引数の説明を書いておくことで、第三者がこのコードを読んだときにスムーズに読み進めることができるようになります。

2024-04-22 01:55 UTC, k-miyahara-being commented on 章未問題2/Practice2-2-3/SalesCounter.cs
フィールド変数とローカル変数の接頭辞をつけてください。

2024-04-22 02:22 UTC, sharlettcho-being commented on 章未問題2/Practice2-1-1/Song.cs
> +        /// <param name="vLength"></param>
修正しました。

2024-04-22 02:22 UTC, sharlettcho-being commented on 章未問題2/Practice2-2-3/SalesCounter.cs
修正しました。

2024-04-22 04:05 UTC, k-miyahara-being commented on 章未問題2/Practice2-2-3/Program.cs
> +            SalesCounter FSales = new SalesCounter(ReadSales("sale.csv"));
ここはローカル変数なので、接頭辞は`w`ですね

2024-04-22 04:32 UTC, sharlettcho-being commented on 章未問題2/Practice2-2-3/Program.cs
> +            SalesCounter FSales = new SalesCounter(ReadSales("sale.csv"));
何回もすみません。
修正しました。

2024-04-22 04:34 UTC, k-miyahara-being approved these changes
OKです！

2024-04-22 04:51 UTC, merged