Feature/#485954
sharlettcho-being/C- pull request #3
Opened 2024-04-16 08:39 UTC by sharlettcho-being

2024-04-23 11:46 UTC, ohdaira-being requested changes
全体的に変数の命名を考え直してほしいです。
田中さんが変数の命名について、以下共有しており、いいサイトでした。
[参考になる単語をまとめてくれているサイト](https://blog.77jp.net/guidelines-for-variables-and-method-names-summary) や [日本語から命名してくれるサイト](https://codic.jp/engine)
是非、参考にしてください。

2024-04-23 11:46 UTC, ohdaira-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +using System.Threading.Tasks;
不要なbusingの削除をお願いします。

2024-04-23 11:46 UTC, ohdaira-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +    internal class Program
クラス・publicメソッド・プロパティには、ドキュメントコメントを付けるようにしてください。

2024-04-23 11:46 UTC, ohdaira-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            var numbers = new List<int> {12, 87, 94, 14, 53, 20, 40, 35, 76, 91, 31, 17, 48};
コーディング規約に従うように変数の命名を修正してください。
他の個所も同様です。

2024-04-23 11:46 UTC, ohdaira-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            var number = numbers.Where(x => x >= 50);
この`number`の命名を考え直してください。
型が何になるかを考えると分かりやすいです。
変数の命名は、単数を表す場合は単数形ろ、複数を表す場合は複数形の命名をします。

2024-04-23 11:46 UTC, ohdaira-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            List<int> query = numbers.Select(x => x * 2).ToList();
右辺で`ToList()`していることから、左辺の型は明らかになっています。
また、`query `の命名も考えなおしてみてください

2024-04-23 11:46 UTC, ohdaira-being commented on 章未問題3/Practice3-1-2/Program3-1-2.cs
> +            else Console.WriteLine(index);
`if(){}else{]`の中括弧（`{}`）は、省略すると可読性が落ち、バグも埋め込みやすいので、省略しないようにしてください。

2024-04-24 01:25 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +using System.Threading.Tasks;
修正しました。

2024-04-24 01:26 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            var numbers = new List<int> {12, 87, 94, 14, 53, 20, 40, 35, 76, 91, 31, 17, 48};
修正しました。

2024-04-24 01:27 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            var number = numbers.Where(x => x >= 50);
修正しました。

2024-04-24 01:28 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-2/Program3-1-2.cs
> +            else Console.WriteLine(index);
修正しました。

2024-04-24 01:30 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            List<int> query = numbers.Select(x => x * 2).ToList();
修正しました。

2024-04-25 08:36 UTC, ohdaira-being requested changes
修正お願いします。

2024-04-25 08:36 UTC, ohdaira-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            var wElements8Or9byDivisibleNumber = wNumbersList.Exists(x => x % 8 == 0 || x % 9 == 0);
こちらの変数名を名前から`bool`型だと分かりやすくしてください。

`wElements8Or9byDivisibleNumber `は、bool型の変数ですね。
`bool`型の変数は、名前からbool型だということが分かりやすくするために
`Is`、`Can`、`Has`といった単語を使います。
今回だと`wHasNumber`といった感じです。

2024-04-25 08:36 UTC, ohdaira-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            wNumbersList.ForEach(elementsDividedByTwo => Console.WriteLine(elementsDividedByTwo / 2.0));
ラムダ式中ですので、`elementsDividedByTwo `は、xで十分かと思います。

2024-04-25 08:36 UTC, ohdaira-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            foreach(var item in wValuesAbove50){
`foreach`の中の`item `も実はローカル変数です。
コーディング規約に合うように変数名を修正してください。

下にもう1か所ありますので、併せてお願いします。

2024-04-25 08:36 UTC, ohdaira-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            List<int> wDoubledValuesList = wNumbersList.Select(x => x * 2).ToList();
ToList()から型が明らかなため、varで十分かと思います。

2024-04-25 08:36 UTC, ohdaira-being commented on 章未問題3/Practice3-1-2/Program3-1-2.cs
> +            }
こちら`wIndex > 0)`の真偽に関わらず、`Console.WriteLine(wIndex);`が実行されるようになっています。
そのため、`ifelse`の場合分けが不要かと思いますので、不要なコードを削除してください。

2024-04-25 08:36 UTC, ohdaira-being commented on 章未問題3/Practice3-1-2/Program3-1-2.cs
> +            foreach(var cityname in wCityNameIncludeLowerCaseO) {
こちらの`cityname `と下の`length`は、ローカル変数なので、変数名の修正お願いします。

2024-04-26 04:15 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-2/Program3-1-2.cs
> +            foreach(var cityname in wCityNameIncludeLowerCaseO) {
修正しました。

2024-04-26 04:15 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-2/Program3-1-2.cs
> +            }
修正しました。

2024-04-26 04:15 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            List<int> wDoubledValuesList = wNumbersList.Select(x => x * 2).ToList();
修正しました。

2024-04-26 04:15 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            foreach(var item in wValuesAbove50){
修正しました。

2024-04-26 04:15 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            wNumbersList.ForEach(elementsDividedByTwo => Console.WriteLine(elementsDividedByTwo / 2.0));
修正しました。

2024-04-26 04:16 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            var wElements8Or9byDivisibleNumber = wNumbersList.Exists(x => x % 8 == 0 || x % 9 == 0);
修正しました。

2024-05-13 05:22 UTC, merged