#485955 [C#テキスト]4章演習問題
sharlettcho-being/C- pull request #4
Opened 2024-04-18 08:09 UTC by sharlettcho-being

2024-04-23 15:07 UTC, ohdaira-being requested changes
コーディング規約に沿っていない箇所がありますので、全体的に確認しながら修正お願いします！

2024-04-23 15:07 UTC, odaira1119 commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +using System.Threading.Tasks;
不要なusingは削除しておいてください

2024-04-23 15:07 UTC, odaira1119 commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            var numbers = new List<int> {12, 87, 94, 14, 53, 20, 40, 35, 76, 91, 31, 17, 48};
全体的に
・ローカル変数
・フィールド変数
・引数
がそれぞれコーディング規約に沿っているか確認をお願いします。

2024-04-23 15:07 UTC, odaira1119 commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            var number = numbers.Where(x => x >= 50);
`number `は、単数を表す変数名になっていますが、実際は複数です。
複数を表す変数には、複数形の命名を行いましょう

2024-04-23 15:07 UTC, odaira1119 commented on 章未問題3/Practice3-1-2/Program3-1-2.cs
> +            index = names.FindIndex(s => s.ToLower() == wCityName.ToLower());
ラムダ式中は、xyzを使います。（コーディング規約）
なので、sをxに修正しておいてください。

2024-04-23 15:07 UTC, ohdaira-being commented on 章未問題3/Practice3-1-2/Program3-1-2.cs
> +            var count2 = names.Where(s => s.Contains('o')).ToArray();
count2という名前からは、都市名の配列だということが読み取れません。
こちらの変数名を考え直してみてください！

2024-04-23 15:07 UTC, ohdaira-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +            else Console.WriteLine(C_MESSAGE2);
中括弧は、省略しないようにお願いします。

2024-04-23 15:07 UTC, ohdaira-being commented on 章未問題4/Practice4-1-1/YearMonth.cs
> +    internal class YearMonth
自前のクラス・publicメソッド・プロパティには、ドキュメントコメントで説明を追加するようにしてください。

2024-04-23 15:07 UTC, ohdaira-being commented on 章未問題4/Practice4-1-2/Program4-1-2.cs
> +            YearMonth[] yearMonths = new YearMonth[5]
右辺から型が明らかなので、varを使う方がすっきりして良くなるかと思います！

2024-04-24 01:43 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +using System.Threading.Tasks;
修正しました。

2024-04-24 01:53 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            var numbers = new List<int> {12, 87, 94, 14, 53, 20, 40, 35, 76, 91, 31, 17, 48};
修正しました。

2024-04-24 01:57 UTC, sharlettcho-being commented on 章未問題4/Practice4-1-1/YearMonth.cs
> +    internal class YearMonth
修正しました。

2024-04-24 01:59 UTC, sharlettcho-being commented on 章未問題4/Practice4-1-2/Program4-1-2.cs
> +            YearMonth[] yearMonths = new YearMonth[5]
修正しました。

2024-04-24 02:10 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-1/Program3-1-1.cs
> +            var number = numbers.Where(x => x >= 50);
修正しました。

2024-04-24 02:10 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-2/Program3-1-2.cs
> +            index = names.FindIndex(s => s.ToLower() == wCityName.ToLower());
修正しました。

2024-04-24 02:10 UTC, sharlettcho-being commented on 章未問題3/Practice3-1-2/Program3-1-2.cs
> +            var count2 = names.Where(s => s.Contains('o')).ToArray();
修正しました。

2024-04-24 02:11 UTC, sharlettcho-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +            else Console.WriteLine(C_MESSAGE2);
修正しました。

2024-05-08 01:51 UTC, ohdaira-being requested changes

2024-05-08 01:51 UTC, ohdaira-being commented on 章未問題4/Practice4-1-1/YearMonth.cs
> +        /// /// <remarks>
`///`が重複しちゃっていますので、修正お願いします。

2024-05-08 01:51 UTC, ohdaira-being commented on 章未問題4/Practice4-1-1/YearMonth.cs
> +            wNewYearMonth.Month = Month;
コンストラクタで代入した後に、再度同じ`Year`、`Month`を代入しています。
不要な処理になりますので、削除してください。

2024-05-08 01:51 UTC, ohdaira-being commented on 章未問題4/Practice4-1-2/Program4-1-2.cs
> +            var wFirst21Century = FindFirst21stCenturyYearMonth(wYearMonths);
最初の21世紀を調べるメソッドを使う方法ではなく、Linqを使って書き直してみてください！

2024-05-08 01:51 UTC, ohdaira-being commented on 章未問題4/Practice4-1-2/YearMonth.cs
> +            wNewYearMonth.Month = Month;
不要なコードを削除してください。

2024-05-08 02:32 UTC, sharlettcho-being commented on 章未問題4/Practice4-1-1/YearMonth.cs
> +        /// /// <remarks>
修正しました。

2024-05-08 02:32 UTC, sharlettcho-being commented on 章未問題4/Practice4-1-1/YearMonth.cs
> +            wNewYearMonth.Month = Month;
修正しました。

2024-05-08 02:40 UTC, sharlettcho-being commented on 章未問題4/Practice4-1-2/Program4-1-2.cs
> +            var wFirst21Century = FindFirst21stCenturyYearMonth(wYearMonths);
修正しました。

2024-05-08 02:41 UTC, sharlettcho-being commented on 章未問題4/Practice4-1-2/YearMonth.cs
> +            wNewYearMonth.Month = Month;
修正しました。

2024-05-09 00:53 UTC, ohdaira-being requested changes
ご確認お願いします！

2024-05-09 00:53 UTC, ohdaira-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +            int wYear = int.Parse(Console.ReadLine());
`int.Parse`でキャスト失敗時（int型にキャストできない文字列を入力した場合）に例外が発生します。
int型にキャストできない文字列を入力された場合も考慮してみてください。
私は、`TryParse`メソッドをよく使います。よかったら、Parseメソッドとの違いも調べてみてください。

2024-05-09 00:53 UTC, ohdaira-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +            int wMonth = int.Parse(Console.ReadLine());
こちらも上記と同様です。
int型にキャストできない文字列を入力された場合も考慮してみてください。

2024-05-09 00:53 UTC, ohdaira-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +                Console.WriteLine(C_MESSAGE2);
三項演算子で書いてみてください。

2024-05-09 00:53 UTC, ohdaira-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +        private static string C_MESSAGE2 = "21世紀ではありません。";
命名を考え直してください。
現在のMESSAGEとMESSAGE2という名前から内容を想像できません。

変数の命名で○○1、○○2といったように数字で分けているものは、その名前でいいのか？と疑うようにすると良いと思います。

2024-05-09 00:53 UTC, ohdaira-being commented on 章未問題4/Practice4-1-2/Program4-1-2.cs
> +            else{
中括弧後に不要な改行がありますので、削除してください。
基本形は以下です。
```
if (条件式) {
// 処理
} else {
// 処理
}
```

2024-05-09 01:09 UTC, sharlettcho-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +            int wYear = int.Parse(Console.ReadLine());
修正しました。
Parseメソッドとの違いも調べてみました。
int.Parseなら文字列が整数ではないなら、例外が発生します。
int.TryParseなら文字列が整数であれば、tureを返す、そうではないならfalseを返します。
整数に変換される文字列が保証されていない場合や入力文字列が不正な場合ならint.TryParseを使った方が良いですね。

2024-05-09 01:09 UTC, sharlettcho-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +            int wMonth = int.Parse(Console.ReadLine());
修正しました。

2024-05-09 01:12 UTC, sharlettcho-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +                Console.WriteLine(C_MESSAGE2);
修正しました。

2024-05-09 01:17 UTC, sharlettcho-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +        private static string C_MESSAGE2 = "21世紀ではありません。";
はい、修正しましたが、三項演算子で変更したので特に定数を宣言しなくもいいと思いますので削除しました。

2024-05-09 01:19 UTC, sharlettcho-being commented on 章未問題4/Practice4-1-2/Program4-1-2.cs
> +            else{
修正しました。

2024-05-10 00:26 UTC, ohdaira-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +            int wYear = int.Parse(Console.ReadLine());
そうですね。
逆にint.Parseが適している場面もあります。
可読性にも関わることですが、
「`Parse`メソッドを使っている」＝「キャスト可能な前提（キャストできない場合は予期しない動作）」
という実装者の考えをコードに反映したい場合です。
各メソッドの違いは、リファレンス等で調べ、更にどういった使い方がされるのかも考えてみるとよりいいコードが欠けるようになると思います！

2024-05-10 00:28 UTC, ohdaira-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +            int wYear = int.Parse(Console.ReadLine());
`int.TryParse(Console.ReadLine(), out int wYear)`がfalseな場合（数字以外の入力な場合）、アプリが急に終了してしまいますので、適切な文字列を表示するようにしましょう

2024-05-10 00:29 UTC, ohdaira-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +            int wMonth = int.Parse(Console.ReadLine());
こちらもfalseな場合に適切な文字列を表示しましょう

2024-05-10 00:30 UTC, ohdaira-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +                Console.WriteLine(C_MESSAGE2);
簡単な条件分岐は、三項演算子で書くとスッキリしますね

2024-05-10 00:32 UTC, ohdaira-being reviewed
追加でコーディング規約違反を修正してください。

2024-05-10 00:32 UTC, ohdaira-being commented on 章未問題4/Practice4-1-1/YearMonth.cs
自クラスのプロパティを参照するときは、thisを付けるというルールです。
7件ほどthisが付けられていませんので、修正お願いします。

2024-05-10 02:23 UTC, sharlettcho-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +            int wYear = int.Parse(Console.ReadLine());
修正しました。

2024-05-10 02:24 UTC, sharlettcho-being commented on 章未問題4/Practice4-1-1/Program4-1-1.cs
> +            int wMonth = int.Parse(Console.ReadLine());
修正しました。

2024-05-10 02:28 UTC, sharlettcho-being commented on 章未問題4/Practice4-1-1/YearMonth.cs
すみません。修正しました。

2024-05-13 05:22 UTC, merged