#485956 [C#テキスト]5章演習問題
sharlettcho-being/C- pull request #5
Opened 2024-04-19 09:20 UTC by sharlettcho-being

5章の演習問題を解きました。

2024-05-08 02:41 UTC, ohdaira-being requested changes
レビューしました。
ご確認ください！

2024-05-08 02:41 UTC, ohdaira-being commented on 章未問題5/Practice5-1-1/Program5-1-1.cs
> +            var wCultureInfo = new CultureInfo("ja-JP");
`wCultureInfo`は、一か所でしか使われていないようですので、使うときに宣言すれば良いかと思います。
なので、不要な変数宣言を削除してください

2024-05-08 02:41 UTC, ohdaira-being commented on 章未問題5/Practice5-1-2/Program5-1-2.cs
> +           int.TryParse(Console.ReadLine(), out wNumber);
`wNumber`の宣言も`TryParse`メソッドの引数内でやってしまいましょう！

2024-05-08 02:41 UTC, ohdaira-being commented on 章未問題5/Practice5-1-3/Program5-1-3.cs
> +            foreach (var wChar in wWords) {
こちらの`wChar` の命名を修正してください
`char`型の文字列のような名前ですが、実際は単語を表しており、誤解を生みます。

2024-05-08 02:41 UTC, ohdaira-being commented on 章未問題5/Practice5-1-3/Program5-1-3.cs
> +            foreach (var wChar in wWords) {
こちらの`wChar `も修正してください

2024-05-08 02:41 UTC, ohdaira-being commented on 章未問題5/Practice5-1-4/Program.cs
> +        /// <returns></returns>
汎用的で使いやすいメソッドですね！
より使いやすくするために、各説明を入れておいてください。

2024-05-08 02:41 UTC, ohdaira-being commented on 章未問題5/Practice5-1-4/Program.cs
> +            return (vText.Substring(wStartIndex, wEndIndex - wStartIndex));
[Substring](https://learn.microsoft.com/ja-jp/dotnet/api/system.string.substring?view=netframework-4.7.2&devlangs=csharp&f1url=%3FappId%3DDev16IDEF1%26l%3DJA-JP%26k%3Dk(System.String.Substring)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%253Dv4.7.2)%3Bk(DevLang-csharp)%26rd%3Dtrue)メソッドは、引数が0未満だと例外を起こしてしまうようです。
現在のコードを見ると、`vText`に`vValue`がない場合に`wStartIndex `が-1となり、`Substring`メソッドに0未満が渉ってしまう可能性があります。
なので、`Substring`メソッドに0未満の値が入らないようにどうするか考えてみてください！

2024-05-08 02:54 UTC, sharlettcho-being commented on 章未問題5/Practice5-1-1/Program5-1-1.cs
> +            var wCultureInfo = new CultureInfo("ja-JP");
修正しました。

2024-05-08 02:55 UTC, sharlettcho-being commented on 章未問題5/Practice5-1-2/Program5-1-2.cs
> +           int.TryParse(Console.ReadLine(), out wNumber);
修正しました。

2024-05-08 02:57 UTC, sharlettcho-being commented on 章未問題5/Practice5-1-3/Program5-1-3.cs
> +            foreach (var wChar in wWords) {
修正しました。

2024-05-08 02:58 UTC, sharlettcho-being commented on 章未問題5/Practice5-1-3/Program5-1-3.cs
> +            foreach (var wChar in wWords) {
修正しました。

2024-05-08 04:03 UTC, sharlettcho-being commented on 章未問題5/Practice5-1-4/Program.cs
> +        /// <returns></returns>
修正しました。

2024-05-08 04:08 UTC, sharlettcho-being commented on 章未問題5/Practice5-1-4/Program.cs
> +            return (vText.Substring(wStartIndex, wEndIndex - wStartIndex));
修正しました。

2024-05-09 01:05 UTC, ohdaira-being commented on 章未問題5/Practice5-1-4/Program.cs
> +        /// <returns></returns>
コード内のコメントではなく、メソッドのXMLドキュメンテーションコメントの`<param>`タグ、`<returns>`タグに説明を追記していただきたいです。
現在、空になっているところです。
誤解させてしまい、すみません。

2024-05-09 01:41 UTC, ohdaira-being commented on 章未問題5/Practice5-1-4/Program.cs
> +            return (vText.Substring(wStartIndex, wEndIndex - wStartIndex));
考えていただき、ありがとうございます。

追加で3点修正お願いします。
①`if(){}else{}`の`else`の前に不要な改行が入っていますので、削除してください。
②条件式を短絡評価で書いてください。
`&`の個所です。
`&`の場合：いつでも`(wStartIndex > 0) `と`(wEndIndex > 0)`の両方が評価されます。
`&&`の場合（短絡評価）：`(wStartIndex > 0) `が`false`な場合、以降の条件を評価しません。
これによって、短絡評価で書いておくことの方がパフォーマンスが良くなることが多いです。
③まだ例外が起きる可能性があります。
`Substring`メソッドは、引数に0未満の値が入ると例外を起こすメソッドです。
`(wStartIndex > 0)` かつ `(wEndIndex > 0)`で条件を記載いただきましたが、
`wEndIndex < wStartIndex `の場合、第二引数に0未満が入る可能性があります。
if条件式を修正しておきましょう。

2024-05-09 01:42 UTC, ohdaira-being commented on 章未問題5/Practice5-1-4/Program.cs
> +        /// <returns></returns>
追加で、修正でnullを返すようにしていますので、
nullを返す可能性があることを説明に入れておくとよいと思います。

2024-05-09 01:51 UTC, sharlettcho-being commented on 章未問題5/Practice5-1-4/Program.cs
> +            return (vText.Substring(wStartIndex, wEndIndex - wStartIndex));
修正しました。

2024-05-13 08:32 UTC, sharlettcho-being commented on 章未問題5/Practice5-1-4/Program.cs
> +        /// <returns></returns>
修正しました。

2024-05-13 08:56 UTC, merged