#485959 [C#テキスト]7章演習問題
sharlettcho-being/C- pull request #7
Opened 2024-04-23 08:56 UTC by sharlettcho-being

7章の演習問題を解きました。

2024-05-10 02:02 UTC, ohdaira-being requested changes
レビューしましたので、ご確認ください！

2024-05-10 02:02 UTC, odaira1119 commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +        static void Main(string[] args) {
Mainメソッドは、最初に実行されるメソッドという普遍的なものですので、基本的にコメントは不要です。
無くてもいいと思います。

2024-05-10 02:02 UTC, odaira1119 commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +            Dictionary<char, int> wDict = new Dictionary<char, int>();
右辺から型が明らかなので、varで良いと思います。

2024-05-10 02:02 UTC, odaira1119 commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +                    }
ネストが深くなっていますので、ガード節で書き直してみてください。
[ガード節について](https://note.com/merucari00/n/nef260fe78abf)
また、書き直す際に正規表現を使ってみてください。

2024-05-10 02:02 UTC, odaira1119 commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
CountAlphabetCharactersUsingDictionaryメソッドとCountAlphabetCharactersUsingSortedDictionaryメソッドについて

①コメント
全く同じコメントで説明していますので、それぞれのメソッドの違い・動作が分かるようなコメント付けるようにしてください

①命名（修正不要）
こちらの両メソッドは、ほとんど同じ単語が続いており、読む際にどっちのメソッドなのかが判断しづらい（読みづらい）ようになっているかと思います。
現在は学習中 かつ 同じ処理を別の型（DictionaryとSortedDictionary）で行う必要があり仕方ないですが、今後を考えると違和感を持ってもらえると良いと思いました。

2024-05-10 02:02 UTC, odaira1119 commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +            foreach (var wItem in wResult) {
wItemが何を表すのか名前から分かりませんので、命名し直してください。

2024-05-10 02:02 UTC, odaira1119 commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +            var wResult = wDict.OrderBy(wpair => wpair.Key);
`wResult `は、一度しか使われていませんので、使うときに`wDict`を`OrderBy`してあげればいいと思います。

2024-05-10 02:02 UTC, odaira1119 commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +            foreach (var item in wSortedDict) {
こちらの`item`も命名し直してください

2024-05-10 02:02 UTC, odaira1119 commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            var lines = File.ReadAllLines("Abbreviations.txt");
読み込むファイルがプッシュされていませんので、
Abbreviations.txtのプッシュをお願いします。
また、該当のファイルが見つからない場合のエラーハンドリングをしておくといいと思います。
（該当ファイルがない場合、`ReadAllLines`で例外が起きてしまうため）

`lines `の命名をコーディング規約に合わせてください。

2024-05-10 02:02 UTC, odaira1119 commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            foreach (var item in FDict) {
`item`の命名を修正してください。

2024-05-10 02:02 UTC, odaira1119 commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            while (FDict.ContainsKey(abbr)) {
whileは、不要かと思いますが、何か意図がありますでしょうか？

2024-05-10 02:02 UTC, odaira1119 commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +        bool wResult = false;
①コーディング規約
`wResult` は、フィールド変数です。

②宣言場所について
この変数は、Dictionaryから削除できたかどうかを表しているかと思います。
フィールド変数にした場合、最初はfalseでも1度削除が成功すると、それ以降ずっとtrueになってしまいます。
また、削除が成功したかどうかを表す変数は、該当のメソッド（Removeメソッド）内にあるのが良いと思います。

2024-05-10 02:02 UTC, odaira1119 commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +        public bool Remove(string abbr) {
`abbr`をコーディング規約に合わせてください。
また、ドキュメントコメントの説明が抜けていますので、追加してください。

2024-05-10 02:02 UTC, odaira1119 commented on 章未問題7/Practice7-1-2/Program7-1-2.cs
> +            foreach (var name in wNames) {
`name `の命名を修正してください。

2024-05-10 02:02 UTC, odaira1119 commented on 章未問題7/Practice7-1-2/Program7-1-2.cs
> +                var wfullname = wAbbrs[name];
`wfullname `のfが小文字になっています！

2024-05-10 02:02 UTC, odaira1119 commented on 章未問題7/Practice7-1-2/Program7-1-2.cs
> +                    Console.WriteLine("{0}は見つかりません。", name);
文字列補間で書くと可読性を高められるので、修正してみてください。

2024-05-10 02:35 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +        static void Main(string[] args) {
修正しました。

2024-05-10 02:37 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +            Dictionary<char, int> wDict = new Dictionary<char, int>();
修正しました。

2024-05-10 02:59 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +            Dictionary<char, int> wDict = new Dictionary<char, int>();
修正しました。

2024-05-10 03:00 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +        static void Main(string[] args) {
修正しました。

2024-05-10 03:00 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +                    }
修正しました。

2024-05-10 03:59 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
修正しました。

2024-05-10 04:02 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +            foreach (var wItem in wResult) {
修正しました。

2024-05-10 04:05 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +        bool wResult = false;
修正しました。

2024-05-10 04:09 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +        public bool Remove(string abbr) {
修正しました。

2024-05-10 04:10 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-2/Program7-1-2.cs
> +            foreach (var name in wNames) {
修正しました。

2024-05-10 04:11 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-2/Program7-1-2.cs
> +                var wfullname = wAbbrs[name];
修正しました。

2024-05-10 04:14 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-2/Program7-1-2.cs
> +                    Console.WriteLine("{0}は見つかりません。", name);
修正しました。

2024-05-13 00:55 UTC, ohdaira-being commented on 章未問題7/Practice7-1-2/Program7-1-2.cs
> +                    Console.WriteLine("{0}は見つかりません。", name);
同様に文字列補完が使われていない箇所が下に7か所ほどありますので、同様に修正してください。

2024-05-13 04:49 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +            var wResult = wDict.OrderBy(wpair => wpair.Key);
修正しました。

2024-05-13 04:50 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +            foreach (var item in wSortedDict) {
修正しました。

2024-05-13 04:56 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            var lines = File.ReadAllLines("Abbreviations.txt");
修正しました。

2024-05-13 04:57 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            foreach (var item in FDict) {
修正しました。

2024-05-13 04:59 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            while (FDict.ContainsKey(abbr)) {
省略語が複数ある場合を考えてwhileを使いました。同じ省略語が複数あるケースがないと思いますのでif に変更しました。

2024-05-13 08:50 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-2/Program7-1-2.cs
> +                    Console.WriteLine("{0}は見つかりません。", name);
修正しました。

2024-05-13 08:59 UTC, ohdaira-being reviewed
追加で修正をお願いします。

2024-05-13 08:59 UTC, odaira1119 commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +            SortedDictionary<char, int> wSortedDict = new SortedDictionary<char, int>();
varにしておきましょう

2024-05-13 08:59 UTC, ohdaira-being commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +            var wResult = wDict.OrderBy(wpair => wpair.Key);
wpair がコーディング規約に合ってないので、修正をお願いします。
コーディング規約に則るとxとなります。

2024-05-13 08:59 UTC, ohdaira-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            foreach (var item in FDict) {
引数のsubstringがコーディング規約に合ってませんので、修正をお願いします。

2024-05-13 08:59 UTC, ohdaira-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            var lines = File.ReadAllLines("Abbreviations.txt");
Abbreviations.txtをプッシュしてください。

2024-05-13 08:59 UTC, ohdaira-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +                this.FDict = wLines.Select(line => line.Split('=')).ToDictionary(x => x[0], x => x[1]);
ここのline もコーディング規約に合わせてください。

2024-05-13 09:04 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-1/Program7-1-1.cs
> +            SortedDictionary<char, int> wSortedDict = new SortedDictionary<char, int>();
修正しました。

2024-05-13 09:10 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +                this.FDict = wLines.Select(line => line.Split('=')).ToDictionary(x => x[0], x => x[1]);
修正しました。
Abbreviations.txtをプッシュは不要と勘違いしてしまいました。^-^

2024-05-14 01:46 UTC, ohdaira-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            }
不要な空行を削除してください。

2024-05-14 01:46 UTC, ohdaira-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            }
例外処理をしていただき、ありがとうございます！
`ReadAllLines`で発生する例外を考慮していただいたかと思います。
今回は複数の種類の例外が考えられるので、例外クラスを指定せずにすべてのExceptionをcatchするようにしたようですね。
この方法もgoodです。

+α
今後扱うシステムが大きくなると、全てのExceptionをcatchすることで、意図しないExceptionを握りつぶしてしまう可能性があります。
そういったときの例外処理はどうすればいいのか？
テキスト（イディオム）の例外を学ぶ章でまた学習してみてください。

2024-05-14 02:18 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            }
catchの前に空行を削除しました。

2024-05-14 02:25 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            }
catch (FileNotFoundException ex) {   }というようにイベントを使うのでしょうか。

2024-05-15 01:12 UTC, ohdaira-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            }
すみません。すごく細かいですが、
catchと}の間にスペースをいれてください。
あと、23行目に不要なスペースがありますので、削除しておいてください。
Visual Studioの設定で テキストエディター>全般 にある空白の表示にチェックを入れておくと見やすいかと思います。

2024-05-15 01:37 UTC, ohdaira-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            }
そうですね。
`throw`で自作の例外を投げることもあります。
詳細まで読んでいないのですが、以下の記事が例外について詳しく書いていそうですので、時間があるときに読んでみてください。
[例外について](https://qiita.com/Kosei-Yoshida/items/8f6aa12d8eab878265a7#%E7%8B%AC%E8%87%AA%E3%81%AE%E4%BE%8B%E5%A4%96%E3%82%AF%E3%83%A9%E3%82%B9%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)

2024-05-15 01:48 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            }
承知しました。

2024-05-15 01:51 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            }
catchと}の間にスペースをいれました。
すみませんが、23行目に不要なスペースが見つからないです。
テキストエディター>全般 にある空白の表示にチェックを入れでも見つからないので。
![image](https://github.com/sharlettcho-being/C-/assets/165862835/ee73dfd4-a56f-481b-b64d-11a9b93fe17c)

2024-05-15 04:40 UTC, sharlettcho-being commented on 章未問題7/Practice7-1-2/Abbreviations.cs
> +            }
不要なスペースを削除しました。

2024-05-16 01:34 UTC, merged