#485962 [C#テキスト]9章演習問題
sharlettcho-being/C- pull request #9
Opened 2024-04-26 00:54 UTC by sharlettcho-being

9章の演習問題を解きました。

2024-05-10 04:20 UTC, ohdaira-being requested changes
数点指摘していますので、修正をお願いします。

2024-05-10 04:20 UTC, odaira1119 commented on 章未問題9/Practice9-1-1/Program9-1-1.cs
> +            var wFilePath = @"C:\SharLettCho\C#研修用\Question3－22\Question3－22\Program.cs";
ファイルパスがチョさんのPC専用の絶対パスになっています。
なので、相対パスを使ってファイルパスを記載するようにしましょう！
下記を参考にして書いてみてください
[相対パスの書き方](https://www.ycomps.co.jp/staffblog/16101)

2024-05-10 04:20 UTC, odaira1119 commented on 章未問題9/Practice9-1-1/CountClass.cs
> +        int wCount = 0;
こちらのフィールド変数は使うときに初期化する方がいいと思います。
`CountLinesContainingClassKeywordUsingStreamReader`と`CountClassKeywords`は、初期化していないので、
`CountLinesContainingClassKeywordUsingStreamReader`した後に`CountClassKeywords`をすると、予期していた数値が返ってこないかと思います。

2024-05-10 04:20 UTC, odaira1119 commented on 章未問題9/Practice9-1-2/Program9-1-2.cs
> +            var wTextFilePathForWrite = @"C:\Users\sharlettcho\Desktop\出力.txt";
こちらのファイルパスも相対パスに修正してください。
また、該当するファイルもプッシュしてください。

2024-05-10 04:20 UTC, odaira1119 commented on 章未問題9/Practice9-1-2/Program9-1-2.cs
> +            if (File.Exists(wTextFilePathForRead)) {
ガード節でネストを浅くしてください。

2024-05-10 04:20 UTC, ohdaira-being commented on 章未問題9/Practice9-1-2/Program9-1-2.cs
> +                        wWriter.WriteLine($"{wLineNumber}: {wLine}");
`wLine`という変数は1か所でのみ使用されており、宣言する必要はないと思います。
そのまま`wReader.ReadLine()`を入れてあげましょう

2024-05-10 04:20 UTC, ohdaira-being commented on 章未問題9/Practice9-1-3/Program9-1-3.cs
> +             string wBetuTextFilePath = args[1];
コマンドライン引数を使って、パスを取得するように実装していただきました。
ただ、コマンドライン引数の内容がpushされていませんので、再度pushお願いします。
また、パスは相対パスで記載し、実行用にテキストファイルを2つ用意してください。

2024-05-10 04:20 UTC, ohdaira-being commented on 章未問題9/Practice9-1-3/Program9-1-3.cs
> +             if (File.Exists(wTextFilePath)) {
こちらもガード節でネストを浅くしてください。

2024-05-10 04:20 UTC, ohdaira-being commented on 章未問題9/Practice9-1-4/Program9-1-4.cs
> +                if (Directory.Exists(wCopyDirectory)) {
ネストが深いので、ガード節で浅くしてください。

2024-05-10 04:20 UTC, ohdaira-being commented on 章未問題9/Practice9-1-4/Program9-1-4.cs
> +            string wCopyDirectory = @"C:\Users\sharlettcho\Desktop\";
相対パスで記載してください。
また、実行用にフォルダを用意してください。

2024-05-10 04:20 UTC, ohdaira-being commented on 章未問題9/Practice9-1-4/Program9-1-4.cs
> +                        string wFilename = Path.GetFileNameWithoutExtension(wFile) + "_bak" + Path.GetExtension(wFile);
+で文字列を繋げてもいいですが、文字列補完を使った方が可読性が高いので、書き直してみてください。

2024-05-10 04:20 UTC, ohdaira-being commented on 章未問題9/Practice9-1-5/Program9-1-5.cs
> +            string wDirectory = @"C:\Users\sharlettcho\Desktop\Test";
パスの修正をお願いします。

2024-05-10 04:43 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-1/Program9-1-1.cs
> +            var wFilePath = @"C:\SharLettCho\C#研修用\Question3－22\Question3－22\Program.cs";
修正しました。

2024-05-10 04:44 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-1/CountClass.cs
> +        int wCount = 0;
修正しました。

2024-05-10 04:51 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-2/Program9-1-2.cs
> +            if (File.Exists(wTextFilePathForRead)) {
修正しました。

2024-05-10 04:52 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-2/Program9-1-2.cs
> +                        wWriter.WriteLine($"{wLineNumber}: {wLine}");
修正しました。

2024-05-10 04:54 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-3/Program9-1-3.cs
> +             if (File.Exists(wTextFilePath)) {
修正しました。

2024-05-10 05:04 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-2/Program9-1-2.cs
> +            var wTextFilePathForWrite = @"C:\Users\sharlettcho\Desktop\出力.txt";
修正しました。

2024-05-10 05:13 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-4/Program9-1-4.cs
> +                if (Directory.Exists(wCopyDirectory)) {
修正しました。

2024-05-10 05:13 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-4/Program9-1-4.cs
> +            string wCopyDirectory = @"C:\Users\sharlettcho\Desktop\";
修正しました。

2024-05-10 05:15 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-4/Program9-1-4.cs
> +                        string wFilename = Path.GetFileNameWithoutExtension(wFile) + "_bak" + Path.GetExtension(wFile);
修正しました。

2024-05-10 05:18 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-5/Program9-1-5.cs
> +            string wDirectory = @"C:\Users\sharlettcho\Desktop\Test";
修正しました。

2024-05-13 04:43 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-3/Program9-1-3.cs
> +             string wBetuTextFilePath = args[1];
修正しました。

2024-05-14 01:45 UTC, ohdaira-being reviewed
すみません。
コメントを送信できていませんでした。
再度、ご確認のほどよろしくお願いします

2024-05-14 01:45 UTC, odaira1119 commented on 章未問題9/Practice9-1-1/CountClass.cs
> +        int wCount = 0;
`CountClassKeywords`メソッドは、`wCount`に0を代入にする処理を通るメソッドから呼ばれるということですね。ありがとうございます。

上記を踏まえて、以下修正お願いします。
`wCount`を各メソッド内で定義してください。
各メソッドが独立して動作し、他のメソッドの実行結果に依存しないようにするためです。
基本的にスコープは最小にすることを意識すると良いです。
スコープについては以下の記事を読んでみてください。
[スコープ](https://gihyo.jp/dev/serial/01/code/000301)

`CountClassKeywords`メソッドの修正も必要だと思います。
分からない場合、聞いてください。

2024-05-14 01:45 UTC, odaira1119 commented on 章未問題9/Practice9-1-1/CountClass.cs
> +            if (File.Exists(vFilePath)) {
ネストが深いので、ガード節で早期リターンしておきましょう。
以下のメソッドも同様です。

2024-05-14 01:45 UTC, odaira1119 commented on 章未問題9/Practice9-1-1/CountClass.cs
> +                //wCount = File.ReadAllLines(vFilePath, Encoding.UTF8).Where(x => x.Contains("class")).Count();
不要なコードは、提出前に削除しておいてください。

2024-05-14 01:45 UTC, odaira1119 commented on 章未問題9/Practice9-1-1/Program9-1-1.cs
> +            var wCountUsingReadLines = wCounterClass.CountLinesContainingClassKeywordUsingReadAllLines(wFilePath);
同じことを繰り返しているようですので、正しく修正してください。
また、以下の変数は、一度しか使われていない かつ CountClassクラスのメソッドを呼んでいるだけですので、変数に取る必要はないです。

- wCountUsingStreamReader 
- wCountUsingReadAllLines 
- wCountUsingReadLines

2024-05-14 01:45 UTC, odaira1119 commented on 章未問題9/Practice9-1-2/Program9-1-2.cs
> +            var wTextFilePathForWrite = @"C:\Users\sharlettcho\Desktop\出力.txt";
該当のファイルも提出してください。

2024-05-14 01:58 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-1/CountClass.cs
> +        int wCount = 0;
wCountを各メソッド内で定義しました。以前はCountClassKeywordsメソッドから返す値を呼び出すメソッドでそのまま受け入れたのでｗCountをCountClassKeywordsメソッドで初期化すると返す値は「０」になりましたので修正できないと思いました。呼び出すメソッドで「＋＝」にすると各メソッドで初期化しても結果が正しくなりました。
有難うございました。

2024-05-14 01:59 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-2/Program9-1-2.cs
> +            var wTextFilePathForWrite = @"C:\Users\sharlettcho\Desktop\出力.txt";
はい、修正しました。

2024-05-14 02:02 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-1/CountClass.cs
> +            if (File.Exists(vFilePath)) {
修正しました。

2024-05-14 02:04 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-1/CountClass.cs
> +                //wCount = File.ReadAllLines(vFilePath, Encoding.UTF8).Where(x => x.Contains("class")).Count();
不要なコードを削除しました。

2024-05-14 02:09 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-1/Program9-1-1.cs
> +            var wCountUsingReadLines = wCounterClass.CountLinesContainingClassKeywordUsingReadAllLines(wFilePath);
変数を使わずにメソッドを直接呼び出して結果を表示しました。

2024-05-15 02:01 UTC, ohdaira-being commented on 章未問題9/Practice9-1-1/CountClass.cs
> +        int wCount = 0;
そうだったんですね。解決されたようで良かったです！

【追加】
現在、同じ行にclassを複数記載しても正しくカウントされないようです。
こちらの件に関して、バグの原因を調査し、修正してみてください。

2024-05-15 02:31 UTC, ohdaira-being reviewed
バグ調査の練習もかねて、指摘しました。
頑張ってください！
もしも分からなければ、聞いてくださって大丈夫です！

2024-05-15 02:31 UTC, ohdaira-being commented on 章未問題9/Practice9-1-1/CountClass.cs
> +            foreach (string line in File.ReadAllLines(vFilePath)) {
line をコーディング規約に合わせてください。

2024-05-15 02:31 UTC, ohdaira-being commented on 章未問題9/Practice9-1-2/Program9-1-2.cs
> +            var wTextFilePathForWrite = @"C:\Users\sharlettcho\Desktop\出力.txt";
パスの修正とファイルの提出ありがとうございます。
正常にどうすることを確認できました。

パスに関して以下のように作成していますが、不要な部分がありますので、修正をお願いします。

> カレントディレクトリパスの取得 → 記載した相対パスと`Combine()`

不要な部分は、カレントディレクトリパスの取得と`Combine()`です。
相対パスだけで十分ですので、不要なコードを削除してください。

2024-05-15 02:31 UTC, ohdaira-being commented on 章未問題9/Practice9-1-3/Program9-1-3.cs
> +             string wBetuTextFilePath = args[1];
ありがとうございます。
ただ、せっかくなので、コマンドライン引数を使って実装してみましょう。
以下の記事を参考にしてみてください。
[コマンドライン引数](https://qiita.com/kelbird/items/9b9039217ef7ff67519e)
もしもそれでも分からない場合は、是非聞いてください。

2024-05-15 02:31 UTC, ohdaira-being commented on 章未問題9/Practice9-1-4/Program9-1-4.cs
> +            string wCopyDirectory = @"C:\Users\sharlettcho\Desktop\";
見逃していました。
こちらもカレントディレクトリパスの取得・パスのCombineは不要ですので、修正お願いします。

2024-05-15 02:31 UTC, ohdaira-being commented on 章未問題9/Practice9-1-5/Program9-1-5.cs
> +            string wDirectory = @"C:\Users\sharlettcho\Desktop\Test";
こちらもカレントディレクトリパスの取得とCombineは不要ですので、修正お願いします。

2024-05-15 02:52 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-2/Program9-1-2.cs
> +            var wTextFilePathForWrite = @"C:\Users\sharlettcho\Desktop\出力.txt";
カレントディレクトリパスの取得とCombine()を削除しました。

2024-05-15 04:04 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-1/CountClass.cs
> +        int wCount = 0;
修正しました。
classを見つかったら、カウントし、breakにしたのがミスでした。breakを削除しました。

2024-05-15 04:17 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-3/Program9-1-3.cs
> +             string wBetuTextFilePath = args[1];
有難うございます。
[コマンドライン引数](https://qiita.com/kelbird/items/9b9039217ef7ff67519e)を参考して修正しましたが、今修正した内容だと相対パスにならないと思います。「構成プロパティ」－「デバック」を選択し、「コマンド引数」の欄」に相対パスを記載すると正しく実行できないので。
よろしくお願いします。

2024-05-15 04:18 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-4/Program9-1-4.cs
> +            string wCopyDirectory = @"C:\Users\sharlettcho\Desktop\";
修正しました。

2024-05-15 04:18 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-5/Program9-1-5.cs
> +            string wDirectory = @"C:\Users\sharlettcho\Desktop\Test";
修正しました。

2024-05-15 04:20 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-1/CountClass.cs
> +            foreach (string line in File.ReadAllLines(vFilePath)) {
wLineとして修正しました。

2024-05-16 00:49 UTC, odaira1119 commented on 章未問題9/Practice9-1-3/Program9-1-3.cs
> +             string wBetuTextFilePath = args[1];
コマンドライン引数に相対パスを記載しても問題ないはずです。
念のため、記載してみて確認しました。

相対パスを記載したときにうまく動かなかったのは、他に原因がありそうです。
再度、相対パスで記載し、問題を解消してみてください。

2024-05-16 00:53 UTC, ohdaira-being commented on 章未問題9/Practice9-1-5/Program9-1-5.cs
> +        static void Main(string[] args) {
Mainメソッドに対してのコメントは不要ですので、削除しておいてください。

2024-05-16 00:59 UTC, odaira1119 reviewed
章未問題9\Practice9-1-5\Testフォルダーは、おそらく不要ですかね？
いろんなファイルが入っていますので、削除しておいた方が良いかと思います

2024-05-16 01:52 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-3/Program9-1-3.cs
> +             string wBetuTextFilePath = args[1];
解決できました。パスの前に@を入れるとうまく動かないのです。

2024-05-16 01:53 UTC, sharlettcho-being commented on 章未問題9/Practice9-1-5/Program9-1-5.cs
> +        static void Main(string[] args) {
気づかないですみません。削除しました。

2024-05-17 01:58 UTC, merged